services:
  - type: web
    name: disbursement-ocr-api
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
